from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from pydantic import BaseModel

from app.database import get_db
from app.models import User, GmailAccount
from app.schemas import (
    UserRegister,
    UserLogin,
    TokenResponse,
    UserOut,
)
from app.auth.security import (
    hash_password,
    verify_password,
    create_access_token,
)
from app.auth.dependencies import get_current_user


router = APIRouter(
    prefix="/api/v1/auth",
    tags=["auth"],
)


class GmailAddonAuthRequest(BaseModel):
    """
    Google Identity Token generated by Apps Script.
    """
    google_id_token: str


@router.post(
    "/register",
    response_model=TokenResponse,
    status_code=status.HTTP_201_CREATED,
)
def register(
    payload: UserRegister,
    db: Session = Depends(get_db),
):
    existing = (
        db.query(User)
        .filter(
            User.email == payload.email.lower()
        )
        .first()
    )

    if existing:
        raise HTTPException(
            status.HTTP_409_CONFLICT,
            "An account with this email already exists",
        )

    user = User(
        email=payload.email.lower(),
        full_name=payload.full_name,
        hashed_password=hash_password(
            payload.password
        ),
    )

    db.add(user)
    db.commit()
    db.refresh(user)

    token = create_access_token(
        subject=str(user.id)
    )

    return TokenResponse(
        access_token=token,
        user=UserOut.model_validate(user),
    )


@router.post(
    "/login",
    response_model=TokenResponse,
)
def login(
    payload: UserLogin,
    db: Session = Depends(get_db),
):
    user = (
        db.query(User)
        .filter(
            User.email == payload.email.lower()
        )
        .first()
    )

    if not user or not verify_password(
        payload.password,
        user.hashed_password,
    ):
        raise HTTPException(
            status.HTTP_401_UNAUTHORIZED,
            "Incorrect email or password",
        )

    if not user.is_active:
        raise HTTPException(
            status.HTTP_403_FORBIDDEN,
            "Account is disabled",
        )

    token = create_access_token(
        subject=str(user.id)
    )

    return TokenResponse(
        access_token=token,
        user=UserOut.model_validate(user),
    )


@router.get(
    "/me",
    response_model=UserOut,
)
def me(
    current_user: User = Depends(get_current_user),
):
    return UserOut.model_validate(
        current_user
    )


@router.post("/gmail-addon")
def gmail_addon_auth(
    payload: GmailAddonAuthRequest,
    db: Session = Depends(get_db),
):
    """
    Authenticate the Gmail Add-on using the
    Google Identity Token generated by Apps Script.

    Flow:

        Gmail user
            ↓
        ScriptApp.getIdentityToken()
            ↓
        MailTrace backend
            ↓
        Verify Google ID token
            ↓
        Extract verified Gmail email
            ↓
        Find GmailAccount
            ↓
        Find linked MailTrace User
            ↓
        Return MailTrace JWT
    """

    google_id_token = (
        payload.google_id_token
        if payload
        else None
    )


    if not google_id_token:

        raise HTTPException(
            status.HTTP_400_BAD_REQUEST,
            "Google identity token is required",
        )


    # Google authentication libraries
    try:

        from google.oauth2 import id_token
        from google.auth.transport import requests as google_requests

    except ImportError:

        raise HTTPException(
            status.HTTP_500_INTERNAL_SERVER_ERROR,
            "Google authentication library is not installed",
        )


 
    GOOGLE_ADDON_CLIENT_ID = (
        "712984633477-3n9klmbm4edroc6m8oensf5eqg1n2dpc"
        ".apps.googleusercontent.com"
    )


    # ---------------------------------------------------------
    # Verify Google Identity Token
    # ---------------------------------------------------------

    try:

        idinfo = id_token.verify_oauth2_token(
            google_id_token,
            google_requests.Request(),
            GOOGLE_ADDON_CLIENT_ID,
        )

    except Exception as exc:

        print(
            "Google identity token verification failed:",
            str(exc),
        )

        raise HTTPException(
            status.HTTP_401_UNAUTHORIZED,
            "Invalid or expired Google identity token",
        )


    # ---------------------------------------------------------
    # Verify issuer
    # ---------------------------------------------------------

    issuer = idinfo.get("iss")

    if issuer not in (
        "accounts.google.com",
        "https://accounts.google.com",
    ):

        raise HTTPException(
            status.HTTP_401_UNAUTHORIZED,
            "Invalid Google token issuer",
        )


    # ---------------------------------------------------------
    # Verify email
    # ---------------------------------------------------------

    email_verified = idinfo.get(
        "email_verified"
    )

    if not email_verified:

        raise HTTPException(
            status.HTTP_401_UNAUTHORIZED,
            "Google email is not verified",
        )


    gmail_address = str(
        idinfo.get(
            "email",
            "",
        )
    ).strip().lower()


    if not gmail_address:

        raise HTTPException(
            status.HTTP_401_UNAUTHORIZED,
            "Could not determine Gmail account",
        )


    # ---------------------------------------------------------
    # Find connected Gmail account
    # ---------------------------------------------------------

    account = (
        db.query(GmailAccount)
        .filter(
            GmailAccount.gmail_address
            == gmail_address
        )
        .first()
    )


    if not account:

        raise HTTPException(
            status.HTTP_403_FORBIDDEN,
            "This Gmail account is not connected to MailTrace AI. "
            "Connect this Gmail account from the MailTrace dashboard first.",
        )


    # ---------------------------------------------------------
    # Find linked MailTrace user
    # ---------------------------------------------------------

    user = (
        db.query(User)
        .filter(
            User.id == account.user_id
        )
        .first()
    )


    if not user:

        raise HTTPException(
            status.HTTP_404_NOT_FOUND,
            "MailTrace user for this Gmail account was not found",
        )


    # ---------------------------------------------------------
    # Check MailTrace account
    # ---------------------------------------------------------

    if not user.is_active:

        raise HTTPException(
            status.HTTP_403_FORBIDDEN,
            "MailTrace account is disabled",
        )


    # ---------------------------------------------------------
    # Create normal MailTrace JWT
    # ---------------------------------------------------------

    token = create_access_token(

        subject=str(user.id),

        extra_claims={
            "purpose": "gmail_addon",
        },

    )


    # ---------------------------------------------------------
    # Return MailTrace authentication
    # ---------------------------------------------------------

    return {

        "access_token":
            token,

        "gmail_address":
            gmail_address,

        "user_id":
            user.id,

    }